version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands: 
      - echo Installing dependencies
      - npm install serverless -g
      - npm install serverless-offline -g

  build:
    commands:
      - echo Deploying serverless application
      - pwd
      - ls
      - serverless deploy --stage dev --verbose --package ./target/dev -v -r ap-south-1
      - echo Deployed successfully