version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands: 
      - echo Installing dependencies
      - npm install serverless -g

  build:
    commands:
      - echo Deploying serverless application
      - pwd
      - serverless deploy --stage dev --package /$CODEBUILD_SRC_DIR/target/dev -v -r ap-south-1
      - echo Deployed successfully