version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands: 
      - echo Installing global dependencies
      - echo Installing serverless
      - npm install serverless -g
      - echo Installing node modules
      - npm install
      - echo Instaling dependencies completed

  build:
    commands:
      - echo Building project
      - mkdir -p target/dev
      - serverless package --package target/dev --stage dev -v -r ap-south-1
      - echo Finished building project

artifacts:
  files:
    - target/dev/*
    - buildspec/deploy/buildspec.deploy.dev.yml
    - serverless.yml
